### ISSUE TITLE
Provide a Bower and NPM support

### ISSUE THREAD

**Issue by jlallement** [matthieuriolo/rivetsjs-stdlib#10]
Is it possible to be compatible with bower and npm ? (just add a bower.json and package.json)
Thx

**Comment by matthieuriolo** [comment]
Hey

I dont use bower neither npm. If you create my the json file I can add it to the repo

**Comment by matthieuriolo** [comment]
AMD and Commonjs module definitions are now available with commit 563ba6fa93d748d48408d1ad4d32d05a5fd102bc
