### ISSUE TITLE
Bower Support: Package not found

### ISSUE THREAD

**Issue by prodrigues** [matthieuriolo/rivetsjs-stdlib#16]
**rivetsjs-stdib** seems to be missing from bower.
When I try to fetch rivetsjs-stdlib from bower it fails with the following message:
`bower                        ENOTFOUND Package rivetsjs-stdlib not found`

Can you make it available through bower again?

**Comment by matthieuriolo** [comment]
try it again

**Comment by prodrigues** [comment]
It works now.

Thanks
