### ISSUE TITLE
Option for including Moment.js

### ISSUE THREAD

**Issue by danhere** [matthieuriolo/rivetsjs-stdlib#8]
I don't need moment.js for what I'm working on and it's not really integral to the library. I think it should be optional to use moment IMHO. Plus it would remove the extra dependency. Just a thought. Thanks for the library though :+1:

**Comment by matthieuriolo** [comment]
Thanks for participating! I made the momentjs library optional, but you cannot use the datetime formatters without it.

**Comment by danhere** [comment]
Oh it is optional? I just installed your library and I get errors that moment is not defined.

**Comment by danhere** [comment]
You rock dude. Thanks again! :+1:

**Comment by matthieuriolo** [comment]
Thanks, it was one of the thing I had already in mind but ... puh ... I did not bother it and no one else ... 
Anyway, thanks for using, thanks for your comments, if you have any suggestions for formatter or binder (or composition, but they seem to be built in a not reusable fashion...) then let me know :)

Cheers and happy coding
